name: GitHub Workflow

on: push

jobs:
  build_test_windows:
    name: Build and test packages (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
        run: yarn
      - name: Bootstrap packages
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
        run: yarn boot
      - name: Test
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
        run: yarn test
